const stages=['ingest','calibration','detection','rhythm','score','validation','dynamics','export'];
const state={project:null,selected:null,socket:null,editPayload:[],editRaw:false};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch('/api/v1'+path,options);if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail);return r.status===204?null:r.json()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function stageSummary(p){return stages.map(s=>`<i class="${p.stages[s].status}"></i>`).join('')}
async function loadProjects(){const projects=await api('/projects');$('#projects').innerHTML=projects.length?projects.map(p=>`<article class="project-card card" data-id="${p.id}"><span class="pill">${esc(p.id)}</span><h3>${esc(p.title)}</h3><div class="mini-graph">${stageSummary(p)}</div><small>${new Date(p.updated_at).toLocaleString()}</small></article>`).join(''):'<p>No projects yet.</p>';document.querySelectorAll('.project-card').forEach(el=>el.onclick=()=>openProject(el.dataset.id))}
async function openProject(id){state.project=await api('/projects/'+id);state.selected=stages.find(s=>['review','failed','running'].includes(state.project.stages[s].status))||stages.find(s=>state.project.stages[s].status!=='complete')||'export';$('#dashboard').hidden=true;$('#workspace').hidden=false;connect(id);render()}
function connect(id){if(state.socket)state.socket.close();const protocol=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${protocol}://${location.host}/api/v1/projects/${id}/events`);state.socket=ws;ws.onopen=()=>$('#connection').textContent='live';ws.onclose=()=>$('#connection').textContent='reconnecting';ws.onmessage=e=>{state.project=JSON.parse(e.data);renderGraph();renderHeader();if(state.project.stages[state.selected]?.status==='running')renderPanel()}}
function render(){renderHeader();renderGraph();renderPanel()}
function renderHeader(){const p=state.project;$('#project-title').textContent=p.title;$('#project-meta').innerHTML=`<span class="pill">${p.id}</span>`}
function renderGraph(){const p=state.project;$('#graph').innerHTML=stages.map((name,i)=>{const s=p.stages[name];return `<div class="stage ${s.status} ${state.selected===name?'active':''}" data-stage="${name}"><div class="stage-icon">${i+1}</div><div class="stage-name">${name}</div><div class="stage-status">${s.status}</div></div>`}).join('');document.querySelectorAll('.stage').forEach(el=>el.onclick=()=>{state.selected=el.dataset.stage;renderGraph();renderPanel()})}
function buttons(name,s){let html='<div class="actions">';if(!['running'].includes(s.status))html+=`<button onclick="runStage('${name}')">${['failed','stale'].includes(s.status)?'Run again':'Run stage'}</button>`;if(s.status==='review')html+=`<button class="approve" onclick="approve('${name}')">Approve and continue</button>`;return html+'</div>'}
async function getData(name){try{return await api(`/projects/${state.project.id}/data/${name}`)}catch{return null}}
async function renderPanel(){const name=state.selected,s=state.project.stages[name],panel=$('#stage-panel');panel.innerHTML=`<p class="eyebrow">STAGE ${stages.indexOf(name)+1}</p><h2>${name[0].toUpperCase()+name.slice(1)}</h2>${s.error?`<div class="error">${esc(s.error)}</div>`:''}<p>${esc(s.message||help[name])}</p><div class="progress"><i style="width:${s.progress*100}%"></i></div>${buttons(name,s)}<div id="stage-content"><p>Loading details…</p></div>`;$('#inspector').innerHTML=`<div class="stat"><span>Status</span><b>${s.status}</b></div><div class="stat"><span>Progress</span><b>${Math.round(s.progress*100)}%</b></div><div class="stat"><span>Approved</span><b>${s.approved?'yes':'no'}</b></div>`;const content=$('#stage-content');if(name==='calibration'){const data=await getData('calibration');if(!data){content.innerHTML='';return}const b=data.bounds;content.innerHTML=`<div class="canvas-wrap"><img class="preview" id="cal-frame" src="/api/v1/projects/${state.project.id}/artifact/calibration-frame"><canvas id="keys"></canvas></div><p>Keyboard bounds</p><div class="actions"><input id="bound-left" type="number" value="${b[0]}" title="Left"><input id="bound-top" type="number" value="${b[1]}" title="Top"><input id="bound-right" type="number" value="${b[2]}" title="Right"><input id="bound-bottom" type="number" value="${b[3]}" title="Bottom"><button onclick="saveBounds()">Redetect keys</button></div><p>Pitch anchor</p><div class="actions"><input id="anchor-index" type="number" min="0" max="${data.keys.length-1}" value="${Math.floor(data.keys.length/2)}" title="Key index"><input id="anchor-midi" type="number" min="0" max="127" value="60" title="MIDI pitch"><button onclick="saveAnchor()">Set pitch anchor</button></div><p>${data.keys.length} keys detected. Confirm the overlays and set one known key to its MIDI pitch when needed (middle C = 60).</p>`;const img=$('#cal-frame');img.onload=()=>drawKeys(data,img,$('#keys'));}
else if(name==='detection'){const notes=await getData('raw-notes');content.innerHTML=notes?noteTable(notes,true):''}
else if(['rhythm','score','dynamics'].includes(name)){const score=await getData('score-data');if(score){content.innerHTML=`<div class="actions"><label>BPM<input id="bpm" type="number" value="${score.bpm}"></label><label>Meter<input id="meter" value="${score.meter.numerator}/${score.meter.denominator}"></label><button onclick="saveSettings()">Re-normalize</button><a class="file-button" href="/api/v1/projects/${state.project.id}/artifact/musicxml">MusicXML</a><a class="file-button" href="/api/v1/projects/${state.project.id}/artifact/midi">MIDI</a></div>${noteTable(score.notes,false)}`}}
else if(name==='validation'){const report=await getData('validation');content.innerHTML=report?`<h3>Timing/energy match: ${Math.round(report.envelope_correlation*100)}%</h3><h3>Pitch-class match: ${Math.round((report.chroma_similarity||0)*100)}%</h3><p>${esc(report.method)} · alignment ${report.alignment_seconds||0}s</p><div class="stat"><span>Source</span><b>${report.source_duration}s</b></div><div class="stat"><span>Rendered</span><b>${report.rendered_duration}s</b></div><h3>Findings (${report.findings.length})</h3>${report.findings.map(f=>`<p class="error">${esc(f.kind)} — note ${esc(f.note_id)}</p>`).join('')}<div class="actions"><audio controls src="/api/v1/projects/${state.project.id}/artifact/source-audio"></audio><audio controls src="/api/v1/projects/${state.project.id}/artifact/rendered-audio"></audio></div>`:''}
else if(name==='export'){const exports=await api(`/projects/${state.project.id}/exports`);content.innerHTML=exports.length?exports.map(f=>`<div class="stat"><a href="/api/v1/projects/${state.project.id}/exports/${encodeURIComponent(f.name)}">${esc(f.name)}</a><span>${Math.round(f.size/1024)} KB</span></div>`).join(''):'<p>Run export after approving validation.</p>'}else content.innerHTML='';}
function noteTable(notes,raw){state.editPayload=structuredClone(notes);state.editRaw=raw;const rows=notes.slice(0,1000).map((n,i)=>noteRow(n,i,raw)).join('');return `<div class="actions"><button onclick="addNote()">Add note</button><button class="approve" onclick="saveNotes()">Save note edits</button></div><div class="scroll-table"><table id="note-table"><thead><tr><th>#</th><th>MIDI</th><th>Onset</th><th>Duration</th><th>Hand</th><th>Confidence</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><small>Showing ${Math.min(1000,notes.length)} of ${notes.length} notes.</small>`}
function noteRow(n,i,raw){return `<tr data-index="${i}"><td>${i+1}</td><td><input class="note-midi" type="number" min="0" max="127" value="${n.midi}"></td><td><input class="note-onset" type="number" min="0" step="0.001" value="${Number(raw?n.onset:n.onset_quarters).toFixed(3)}"></td><td><input class="note-duration" type="number" min="0.001" step="0.001" value="${Number(raw?n.offset-n.onset:n.duration_quarters).toFixed(3)}"></td><td><select class="note-hand"><option value="left" ${n.hand==='left'?'selected':''}>left</option><option value="right" ${n.hand==='right'?'selected':''}>right</option></select></td><td>${Math.round((n.confidence??1)*100)}%</td><td><button class="danger" onclick="deleteNote(${i})">×</button></td></tr>`}
function drawKeys(data,img,canvas){canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');ctx.lineWidth=1;ctx.font='10px monospace';data.keys.forEach((k,i)=>{ctx.beginPath();k.polygon.forEach((p,j)=>j?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.strokeStyle=k.kind==='black'?'#58b7ff':'#ff6040';ctx.stroke();if(i%4===0){const p=k.polygon[2];ctx.fillStyle='#ffdf54';ctx.fillText(`${i}:${k.midi}`,p[0]-12,p[1]-3)}})}
async function runStage(name){await api(`/projects/${state.project.id}/stages/${name}/run`,{method:'POST'});toast('Stage started')}
async function approve(name){await api(`/projects/${state.project.id}/stages/${name}/approve`,{method:'POST'});toast('Approved; continuing')}
async function saveAnchor(){await api(`/projects/${state.project.id}/calibration/anchor`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key_index:+$('#anchor-index').value,midi:+$('#anchor-midi').value})});toast('Pitch anchor saved');renderPanel()}
async function saveBounds(){await api(`/projects/${state.project.id}/calibration/bounds`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({left:+$('#bound-left').value,top:+$('#bound-top').value,right:+$('#bound-right').value,bottom:+$('#bound-bottom').value})});toast('Keyboard bounds updated');renderPanel()}
function collectNotes(){document.querySelectorAll('#note-table tbody tr').forEach(row=>{const i=+row.dataset.index,n=state.editPayload[i];if(!n||n._deleted)return;const onset=+row.querySelector('.note-onset').value,duration=+row.querySelector('.note-duration').value;n.midi=+row.querySelector('.note-midi').value;n.hand=row.querySelector('.note-hand').value;if(state.editRaw){n.onset=onset;n.offset=onset+duration}else{n.onset_quarters=onset;n.duration_quarters=duration}});return state.editPayload.filter(n=>!n._deleted).map(n=>{delete n._deleted;return n})}
function deleteNote(index){state.editPayload[index]._deleted=true;document.querySelector(`#note-table tr[data-index="${index}"]`).remove()}
function addNote(){const raw=state.editRaw,n=raw?{id:crypto.randomUUID().replaceAll('-','').slice(0,12),midi:60,onset:0,offset:.5,confidence:1,hand:'right',evidence:{manual:true}}:{id:crypto.randomUUID().replaceAll('-','').slice(0,12),midi:60,onset_quarters:0,duration_quarters:1,confidence:1,hand:'right',voice:1,velocity:72};const i=state.editPayload.push(n)-1;$('#note-table tbody').insertAdjacentHTML('beforeend',noteRow(n,i,raw))}
async function saveNotes(){const notes=collectNotes();if(state.editRaw){await api(`/projects/${state.project.id}/data/raw-notes`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(notes)})}else{const score=await getData('score-data');score.notes=notes;await api(`/projects/${state.project.id}/data/score-data`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(score)})}toast('Note edits saved; downstream stages are stale');state.project=await api('/projects/'+state.project.id);renderGraph()}
async function saveSettings(){await api(`/projects/${state.project.id}/settings`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({bpm:+$('#bpm').value,meter:$('#meter').value})});toast('Timing settings saved');state.project=await api('/projects/'+state.project.id);state.selected='rhythm';render()}
const help={ingest:'Download or copy the source and extract analysis audio.',calibration:'Find the first stable keyboard and map its keys.',detection:'Track color changes into raw note events.',rhythm:'Choose a clean fixed tempo and meter.',score:'Assign hands, voices, pitches, and clefs.',validation:'Render the notation and compare it to the source audio.',dynamics:'Normalize note energy into musical dynamics.',export:'Create MusicXML, MIDI, PDF, audio, and a project archive.'};
$('#url-form').onsubmit=async e=>{e.preventDefault();try{const p=await api('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:$('#source').value})});openProject(p.id)}catch(e){toast(e.message)}};
$('#upload-form').onsubmit=async e=>{e.preventDefault();const data=new FormData();data.append('file',$('#upload').files[0]);try{const p=await api('/projects/upload',{method:'POST',body:data});openProject(p.id)}catch(e){toast(e.message)}};
$('#back').onclick=()=>{if(state.socket)state.socket.close();$('#workspace').hidden=true;$('#dashboard').hidden=false;loadProjects()};$('#refresh').onclick=loadProjects;window.runStage=runStage;window.approve=approve;window.saveAnchor=saveAnchor;window.saveBounds=saveBounds;window.saveSettings=saveSettings;window.saveNotes=saveNotes;window.addNote=addNote;window.deleteNote=deleteNote;loadProjects();
