const stages=['ingest','calibration','detection','rhythm','score','validation','dynamics','export'];
const state={project:null,selected:null,socket:null,regions:[],notes:[],raw:false,version:0,animation:null};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch('/api/v1'+path,options);if(!r.ok){const b=await r.json().catch(()=>({detail:r.statusText}));throw new Error(typeof b.detail==='string'?b.detail:JSON.stringify(b.detail))}return r.status===204?null:r.json()}
function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
async function safe(fn){try{return await fn()}catch(e){toast(e.message)}}
async function data(name){try{return await api(`/projects/${state.project.id}/data/${name}`)}catch{return null}}
function summary(p){return stages.map(s=>`<i class="${p.stages[s]?.status||'pending'}"></i>`).join('')}
async function loadProjects(){await safe(async()=>{const ps=await api('/projects');$('#projects').innerHTML=ps.length?ps.map(p=>`<article class="project-card card" data-id="${p.id}"><span class="pill">${p.id}</span><h3>${esc(p.title)}</h3><div class="mini-graph">${summary(p)}</div><small>${new Date(p.updated_at).toLocaleString()}</small></article>`).join(''):'<p>No projects yet.</p>';document.querySelectorAll('.project-card').forEach(e=>e.onclick=()=>openProject(e.dataset.id))})}
async function openProject(id){await safe(async()=>{state.project=await api('/projects/'+id);state.selected=stages.find(s=>['review','failed','running'].includes(state.project.stages[s].status))||stages.find(s=>state.project.stages[s].status!=='complete')||'validation';$('#dashboard').hidden=true;$('#workspace').hidden=false;connect(id);render()})}
function connect(id){state.socket?.close();const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/v1/projects/${id}/events`);state.socket=ws;ws.onopen=()=>$('#connection').textContent='live';ws.onclose=()=>$('#connection').textContent='offline';ws.onmessage=e=>{const old=state.project?.stages[state.selected];state.project=JSON.parse(e.data);header();graph();const now=state.project.stages[state.selected];if(!old||old.status!==now.status||old.error!==now.error)panel();else{$('#stage-panel .progress i')?.style.setProperty('width',`${now.progress*100}%`);const x=$('#inspector .progress-value');if(x)x.textContent=`${Math.round(now.progress*100)}%`}}}
function render(){header();graph();panel()}function header(){$('#project-title').textContent=state.project.title;$('#project-meta').innerHTML=`<span class="pill">${state.project.id}</span>`}
function graph(){$('#graph').innerHTML=stages.map((n,i)=>{const s=state.project.stages[n];return `<div class="stage ${s.status} ${state.selected===n?'active':''}" data-stage="${n}"><div class="stage-icon">${i+1}</div><div class="stage-name">${n}</div><div class="stage-status">${n==='dynamics'?'disabled':s.status}</div></div>`}).join('');document.querySelectorAll('.stage').forEach(e=>e.onclick=()=>{state.selected=e.dataset.stage;graph();panel()})}
function buttons(n,s){return `<div class="actions">${s.status!=='running'&&n!=='dynamics'?`<button onclick="runStage('${n}')">${['failed','stale'].includes(s.status)?'Run again':'Run stage'}</button>`:''}${s.status==='review'?`<button class="approve" onclick="approve('${n}')">Approve and continue</button>`:''}</div>`}
async function panel(){const v=++state.version;if(state.animation)cancelAnimationFrame(state.animation);const n=state.selected,s=state.project.stages[n],p=$('#stage-panel');p.innerHTML=`<p class="eyebrow">STAGE ${stages.indexOf(n)+1}</p><h2>${n[0].toUpperCase()+n.slice(1)}</h2>${s.error?`<div class="error">${esc(s.error)}</div>`:''}<p>${esc(s.message||help[n])}</p><div class="progress"><i style="width:${s.progress*100}%"></i></div>${buttons(n,s)}<div id="stage-content"><p>Loading…</p></div>`;$('#inspector').innerHTML=`<div class="stat"><span>Status</span><b>${n==='dynamics'?'disabled':s.status}</b></div><div class="stat"><span>Progress</span><b class="progress-value">${Math.round(s.progress*100)}%</b></div>`;const c=$('#stage-content');if(n==='calibration')await calibration(c);else if(n==='detection'){const x=await data('raw-notes');if(v===state.version)c.innerHTML=x?noteTable(x,true):'<p>Save and approve manual key regions first.</p>'}else if(['rhythm','score'].includes(n))await score(c,v);else if(n==='validation')await validation(c,v);else if(n==='dynamics')c.innerHTML='<div class="notice"><h3>Dynamics disabled</h3><p>No dynamics, crescendos, decrescendos, velocity normalization, or timing cleanup is applied.</p></div>';else if(n==='export')await exports(c,v);else c.innerHTML=''}
async function calibration(c){const d=await data('calibration');if(!d){c.innerHTML='<p>Run calibration after ingest.</p>';return}state.regions=d.mode==='manual-regions'?d.keys.map(k=>({midi:k.midi,left:k.polygon[0][0],top:k.polygon[0][1],right:k.polygon[2][0],bottom:k.polygon[2][1],threshold:k.threshold||14,hand:k.hand||null})):[];c.innerHTML=`<div class="notice"><b>Manual mode:</b> drag a tight box inside every key where its colour changes. The displayed frame must show that key unlit.</div><div class="canvas-wrap manual"><img class="preview" id="cal-frame" src="/api/v1/projects/${state.project.id}/artifact/calibration-frame"><canvas id="keys"></canvas></div><div class="draw-tools"><label>Next MIDI<input id="region-midi" type="number" min="0" max="127" value="60"></label><label>Threshold<input id="region-threshold" type="number" min="2" max="100" value="14"></label><label>Hand<select id="region-hand"><option value="">auto</option><option>left</option><option>right</option></select></label><button class="secondary" onclick="clearRegions()">Clear</button><button class="approve" onclick="saveRegions()">Save regions</button></div><div id="region-list"></div>`;const image=$('#cal-frame');image.onload=()=>regionCanvas(image,$('#keys'));if(image.complete)regionCanvas(image,$('#keys'));regionList()}
function point(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
function regionCanvas(image,c){c.width=image.naturalWidth;c.height=image.naturalHeight;drawRegions();let start;c.onpointerdown=e=>{start=point(e,c);c.setPointerCapture(e.pointerId)};c.onpointerup=e=>{if(!start)return;const end=point(e,c),r={midi:+$('#region-midi').value,left:Math.min(start.x,end.x),top:Math.min(start.y,end.y),right:Math.max(start.x,end.x),bottom:Math.max(start.y,end.y),threshold:+$('#region-threshold').value,hand:$('#region-hand').value||null};start=null;if(r.right-r.left<3||r.bottom-r.top<3)return toast('Draw a larger box');state.regions.push(r);$('#region-midi').value=Math.min(127,r.midi+1);drawRegions();regionList()}}
function drawRegions(){const c=$('#keys');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.font='bold 15px monospace';x.lineWidth=2;state.regions.forEach((r,i)=>{x.fillStyle=i%2?'#386b8d44':'#d64b2a44';x.strokeStyle=i%2?'#58b7ff':'#ff6040';x.fillRect(r.left,r.top,r.right-r.left,r.bottom-r.top);x.strokeRect(r.left,r.top,r.right-r.left,r.bottom-r.top);x.fillStyle='#fff';x.fillText(r.midi,r.left+4,r.top+17)})}
function regionList(){const e=$('#region-list');if(e)e.innerHTML=state.regions.length?`<div class="scroll-table"><table><thead><tr><th>#</th><th>MIDI</th><th>Hand</th><th>Threshold</th><th></th></tr></thead><tbody>${state.regions.map((r,i)=>`<tr><td>${i+1}</td><td>${r.midi}</td><td>${r.hand||'auto'}</td><td>${r.threshold}</td><td><button class="danger" onclick="removeRegion(${i})">×</button></td></tr>`).join('')}</tbody></table></div>`:'<p>Drag on the frame to add a key.</p>'}
function removeRegion(i){state.regions.splice(i,1);drawRegions();regionList()}function clearRegions(){state.regions=[];drawRegions();regionList()}
async function saveRegions(){await safe(async()=>{await api(`/projects/${state.project.id}/calibration/regions`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({regions:state.regions})});toast(`Saved ${state.regions.length} key regions`);state.project=await api('/projects/'+state.project.id);graph()})}
async function score(c,v){const s=await data('score-data');if(v!==state.version)return;if(!s){c.innerHTML='<p>Run after detection.</p>';return}const rendered=['review','complete'].includes(state.project.stages.score.status);c.innerHTML=`<div class="notice"><b>Exact timestamp mode.</b> BPM only changes written scale; it does not snap events.</div><div class="actions"><label>BPM<input id="bpm" type="number" value="${s.bpm}"></label><label>Meter<input id="meter" value="${s.meter.numerator}/${s.meter.denominator}"></label><button onclick="saveSettings()">Rebuild</button>${rendered?`<a class="file-button" href="/api/v1/projects/${state.project.id}/artifact/musicxml">MusicXML</a><a class="file-button" href="/api/v1/projects/${state.project.id}/artifact/midi">MIDI</a>`:''}</div><canvas id="piano-roll" class="piano-roll" width="1000" height="380"></canvas>${rendered?`<iframe class="score-preview" src="/api/v1/projects/${state.project.id}/artifact/score-preview"></iframe>`:''}${noteTable(s.notes,false)}`;pianoRoll($('#piano-roll'),s,0,false)}
async function validation(c,v){const [r,s]=await Promise.all([data('validation'),data('score-data')]);if(v!==state.version)return;if(!r||!s){c.innerHTML='<p>Run validation to create transcription audio.</p>';return}const duration=Math.max(r.source_duration||0,r.rendered_duration||0);c.innerHTML=`<div class="playback"><h3>Original + transcription</h3><p>A single transport starts both at the same timestamp.</p><canvas id="live-roll" class="piano-roll" width="1000" height="420"></canvas><div class="transport"><button id="play-both">▶ Play both</button><button class="secondary" id="pause-both">Pause</button><input id="seek-both" type="range" min="0" max="${duration}" step=".01" value="0"><output id="play-time">0.00s</output></div><div class="audio-pair"><label>Original<audio id="source-player" controls preload="metadata" src="/api/v1/projects/${state.project.id}/artifact/source-audio"></audio></label><label>Transcription<audio id="rendered-player" controls preload="metadata" src="/api/v1/projects/${state.project.id}/artifact/rendered-audio"></audio></label></div></div><div class="stat"><span>Pitch match</span><b>${Math.round((r.chroma_similarity||0)*100)}%</b></div><div class="stat"><span>Timing/energy match</span><b>${Math.round((r.envelope_correlation||0)*100)}%</b></div><h3>Findings (${r.findings.length})</h3>${r.findings.slice(0,200).map(f=>`<p class="error">${esc(f.kind)} — ${esc(f.note_id)}</p>`).join('')}`;playback(s)}
function seconds(n,s){const q=60/s.bpm;return{on:n.onset_quarters*q,off:(n.onset_quarters+n.duration_quarters)*q}}
function pianoRoll(c,s,time=0,falling=false){if(!c)return;const x=c.getContext('2d'),ns=s.notes,w=c.width,h=c.height,k=55;x.fillStyle='#111';x.fillRect(0,0,w,h);if(!ns.length)return;const lo=Math.min(...ns.map(n=>n.midi))-2,hi=Math.max(...ns.map(n=>n.midi))+2,span=hi-lo+1,px=p=>(p-lo)/span*w,window=falling?6:Math.max(8,...ns.map(n=>seconds(n,s).off)),scale=(h-k)/window;for(const n of ns){const t=seconds(n,s);let y=falling?h-k-(t.on-time)*scale:8+t.on*scale,nh=Math.max(3,(t.off-t.on)*scale);if(y<0||y-nh>h-k)continue;x.fillStyle=n.hand==='left'?'#d64b2acc':'#58b7ffcc';x.fillRect(px(n.midi)+1,y-nh,Math.max(3,w/span-2),nh)}x.fillStyle='#f7f3e8';x.fillRect(0,h-k,w,k);for(let p=lo;p<=hi;p++)if([1,3,6,8,10].includes((p%12+12)%12)){x.fillStyle='#222';x.fillRect(px(p),h-k,w/span*.7,k*.62)}if(falling){x.strokeStyle='#f2c35e';x.lineWidth=3;x.beginPath();x.moveTo(0,h-k);x.lineTo(w,h-k);x.stroke()}}
function playback(s){const a=$('#source-player'),b=$('#rendered-player'),seek=$('#seek-both'),out=$('#play-time'),canvas=$('#live-roll');const frame=()=>{const t=a.currentTime||0;if(Math.abs((b.currentTime||0)-t)>.08)b.currentTime=t;seek.value=t;out.textContent=`${t.toFixed(2)}s`;pianoRoll(canvas,s,t,true);if(!a.paused)state.animation=requestAnimationFrame(frame)};$('#play-both').onclick=async()=>{b.currentTime=a.currentTime;await Promise.allSettled([a.play(),b.play()]);frame()};$('#pause-both').onclick=()=>{a.pause();b.pause()};seek.oninput=()=>{a.currentTime=+seek.value;b.currentTime=+seek.value;pianoRoll(canvas,s,+seek.value,true);out.textContent=`${(+seek.value).toFixed(2)}s`};pianoRoll(canvas,s,0,true)}
async function exports(c,v){const fs=await api(`/projects/${state.project.id}/exports`);if(v===state.version)c.innerHTML=fs.length?fs.map(f=>`<div class="stat"><a href="/api/v1/projects/${state.project.id}/exports/${encodeURIComponent(f.name)}">${esc(f.name)}</a><span>${Math.round(f.size/1024)} KB</span></div>`).join(''):'<p>No exports yet.</p>'}
function noteTable(ns,raw){state.notes=structuredClone(ns);state.raw=raw;return `<div class="actions"><button onclick="addNote()">Add note</button><button class="approve" onclick="saveNotes()">Save edits</button></div><div class="scroll-table"><table id="note-table"><thead><tr><th>#</th><th>MIDI</th><th>Onset</th><th>Duration</th><th>Hand</th><th></th></tr></thead><tbody>${ns.slice(0,1000).map((n,i)=>noteRow(n,i,raw)).join('')}</tbody></table></div><small>Showing ${Math.min(1000,ns.length)} of ${ns.length}.</small>`}
function noteRow(n,i,raw){return `<tr data-index="${i}"><td>${i+1}</td><td><input class="note-midi" type="number" value="${n.midi}"></td><td><input class="note-onset" type="number" step=".001" value="${Number(raw?n.onset:n.onset_quarters).toFixed(3)}"></td><td><input class="note-duration" type="number" step=".001" value="${Number(raw?n.offset-n.onset:n.duration_quarters).toFixed(3)}"></td><td><select class="note-hand"><option ${n.hand==='left'?'selected':''}>left</option><option ${n.hand==='right'?'selected':''}>right</option></select></td><td><button class="danger" onclick="deleteNote(${i})">×</button></td></tr>`}
function collect(){document.querySelectorAll('#note-table tbody tr').forEach(r=>{const n=state.notes[+r.dataset.index],on=+r.querySelector('.note-onset').value,d=+r.querySelector('.note-duration').value;n.midi=+r.querySelector('.note-midi').value;n.hand=r.querySelector('.note-hand').value;if(state.raw){n.onset=on;n.offset=on+d}else{n.onset_quarters=on;n.duration_quarters=d}});return state.notes.filter(n=>!n.deleted)}function deleteNote(i){state.notes[i].deleted=true;document.querySelector(`#note-table tr[data-index="${i}"]`)?.remove()}function addNote(){const n=state.raw?{id:crypto.randomUUID().slice(0,12),midi:60,onset:0,offset:.5,confidence:1,hand:'right'}:{id:crypto.randomUUID().slice(0,12),midi:60,onset_quarters:0,duration_quarters:1,hand:'right',voice:1};const i=state.notes.push(n)-1;$('#note-table tbody').insertAdjacentHTML('beforeend',noteRow(n,i,state.raw))}
async function saveNotes(){await safe(async()=>{const ns=collect();if(state.raw)await api(`/projects/${state.project.id}/data/raw-notes`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(ns)});else{const s=await data('score-data');s.notes=ns;await api(`/projects/${state.project.id}/data/score-data`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)})}toast('Edits saved')})}
async function runStage(n){await safe(async()=>{await api(`/projects/${state.project.id}/stages/${n}/run`,{method:'POST'});toast('Stage started')})}async function approve(n){await safe(async()=>{state.project=await api(`/projects/${state.project.id}/stages/${n}/approve`,{method:'POST'});toast('Approved');graph()})}async function saveSettings(){await safe(async()=>{await api(`/projects/${state.project.id}/settings`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({bpm:+$('#bpm').value,meter:$('#meter').value})});state.project=await api('/projects/'+state.project.id);render();toast('Rebuild requested; raw timestamps unchanged')})}
const help={ingest:'Acquire video and audio.',calibration:'Draw exact key regions.',detection:'Record visible on/off transitions.',rhythm:'Preserve video timestamps at a display BPM.',score:'Group pitch clusters into hands and render notation.',validation:'Play original and transcription together.',dynamics:'Disabled.',export:'Create score files.'};
$('#url-form').onsubmit=e=>{e.preventDefault();safe(async()=>openProject((await api('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:$('#source').value})})).id))};$('#upload-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const f=$('#upload').files[0];if(!f)throw new Error('Choose a video');const d=new FormData();d.append('file',f);openProject((await api('/projects/upload',{method:'POST',body:d})).id)})};$('#back').onclick=()=>{state.socket?.close();state.project=null;$('#workspace').hidden=true;$('#dashboard').hidden=false;loadProjects()};$('#refresh').onclick=loadProjects;Object.assign(window,{runStage,approve,saveSettings,saveNotes,addNote,deleteNote,saveRegions,removeRegion,clearRegions});loadProjects();
